spring.application.name=task-manager
server.port=8088

spring.datasource.url=jdbc:postgresql://postgres:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=Manmohan@373
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


security.jwt.secret=task-manager-secret-key-123456789
security.jwt.expiration-ms=3600000

